export default [
	{
		path:'/pages/home/index',name:'home/index',
	},
	{
		path:'/pages/firList/index',name:'firList/index',
	},
	{
		path:'/pages/voiceSend/index',name:'voiceSend/index',
	},
	{
		path:'/pages/mine/index',name:'mine/index',
	},
	{
		path:'/pages/mine/login',name:'mine/login',
	},
	{
		path:'/pages/mine/register',name:'mine/register',
	},
]